apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-app-sa-binding
  namespace: dev
subjects:
  - kind: ServiceAccount
    name: my-app-sa
    namespace: dev
roleRef:
  kind: Role
  name: my-app-readonly-role
  apiGroup: rbac.authorization.k8s.io
