apiVersion: v1
kind: ResourceQuota
metadata:
  name: my-app-quota
spec:
  hard:
    pods: "10"                   # Maximum of 10 pods in this namespace
    requests.cpu: "2"             # Total CPU requests cannot exceed 2 cores
    requests.memory: "4Gi"        # Total memory requests cannot exceed 4Gi
    limits.cpu: "4"               # Total CPU limits cannot exceed 4 cores
    limits.memory: "8Gi"          # Total memory limits cannot exceed 8Gi
    services: "5"                 # Maximum of 5 services in this namespace
    persistentvolumeclaims: "2"   # Maximum of 2 PVCs in this namespace
