apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: my-app-readonly-role
  namespace: dev
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
