apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- namespace.yaml
- rbac.yaml
- limitrange.yaml
- resourcequoata.yaml
- serviceaccount.yaml
- role.yaml

# Dinamik olarak image tag değiştirme
images:
  - name: miraccan/servicename
    newTag: dev-latest  # Buraya istediğiniz image tag'i yazabilirsiniz
