apiVersion: v1
kind: LimitRange
metadata:
  name: container-limits
  namespace: dev
spec:
  limits:
    - type: Container  # Apply limits at the container level
      default:
        cpu: "500m"      # Default CPU limit (0.5 core)
        memory: "512Mi"  # Default memory limit
      defaultRequest:
        cpu: "250m"      # Default CPU request (0.25 core)
        memory: "256Mi"  # Default memory request
      max:
        cpu: "2"         # Maximum CPU limit per container
        memory: "2Gi"    # Maximum memory limit per container
      min:
        cpu: "100m"      # Minimum CPU request per container
        memory: "128Mi"  # Minimum memory request per container
